GET http://localhost:3001/contacts

###

POST http://localhost:3001/contacts/new
Content-Type: application/json

{
    "firstName" : "Maricia",
    "lastName" : "Aubourg",
    "phoneNumber": 7187878606
}


###
DELETE http://localhost:3001/contacts/delete/62104a01ef1962067af4ecc6

###

PUT http://localhost:3001/contacts/complete/620f4170bdd544376f3e9b1f